version: "3"
services:


       backend:
           container_name: volopa-backend
           image: latest/volopa-backend
           environment: 
              NODE_ENV: development
              BASE_URL: http://localhost
              PORT: 4000
              MONGO_URL: mongodb://mongo:27017/mydb
              API_VERSION: v1
              

           restart: always
           build:
              context: ./backend
              dockerfile: ./Dockerfile
           ports:
             - "4000:4000"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27017:27017'

       client:
          container_name: volopa-client
          image: latest/volopa-client
          environment: 
            NODE_ENV: development
            API_URL: http://localhost:4000
            PORT: 3000

          restart: always
          build: 
            context: ./client
            dockerfile: ./Dockerfile
          ports:
            - "3000:3000"
          links:
            - "backend:be"
